#!/bin/sh

# # Inspired by https://github.com/thoughtbot/laptop
#
# # Install Homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

#
# # Brew
brew update --force

brew bundle --file=-<<EOF
tap "homebrew/services"
tap "universal-ctags/universal-ctags"
tap "caskroom/cask"
tap "heroku/brew"

brew "git"
brew "openssl"
brew "the_silver_searcher"
brew "tmux"
brew "vim"
brew "zsh"
brew "postgresql"
brew "redis"
brew "fzf"
brew "fd"
brew "yarn"
brew "mas"
brew "tree"

# Casks
cask "google-chrome"
cask "iterm2"
cask "1password"
cask "dropbox"
EOF

# Mas-es

# Amphetemine
mas install 937984704
